name: API specs continuous integration

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Markdown Linting Action
      uses: nosborn/github-action-markdown-cli@v1.1.1
